artifacts_root: artifacts

data ingestion:
  root dir: artifacts/data_ingestion
  source: data/textures 3
  data_dir: artifacts/data_ingestion/fabric_data
  STATUS_FILE: artifacts/data_ingestion/status.txt

data validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/fabric_data
  STATUS_FILE: artifacts/data_validation/status.txt  # status of data validation 

image_processing:
  root_dir: artifacts/image_processing
  data_dir: artifacts/data_ingestion/fabric_data
  STATUS_FILE: artifacts/image_processing/status.txt

feature_extraction:
  root_dir: artifacts/feature_extraction
  data_dir: artifacts/data_ingestion/fabric_data
  STATUS_FILE: artifacts/feature_extraction/status.txt

feature_engineering:
  root_dir: artifacts/feature_engineering
  data_dir: artifacts/data_ingestion/fabric_data
  STATUS_FILE: artifacts/feature_engineering/status.txt

#Changes will need to be done for model_trainer and model_evaluation as we are doing a nested cross validation
model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json