artifacts_root: artifacts_deployment

feature_extraction:
  root_dir: artifacts_deployment/feature_extraction
  data_dir: artifacts_deployment/image_processing/processed_images
  STATUS_FILE: artifacts_deployment/feature_extraction/status.txt

feature_engineering:
  root_dir: artifacts_deployment/feature_engineering
  pipeline: artifacts/feature_engineering/pipeline.joblib
  extracted_features: artifacts_deployment/feature_extraction
  STATUS_FILE: artifacts_deployment/feature_engineering/status.txt

# Will make changes
nested_cross_val:
  root_dir: artifacts/nested_cross_val
  extracted_features:  artifacts/feature_extraction
  random_search_models_rf: artifacts/nested_cross_val/random_search_models/random_forest
  model_cache_rf: artifacts/nested_cross_val/model_cache_rf
  #random_search_models_svm: artifacts/nested_cross_val/random_search_models/svm - If required use
  #model_cache_svm: artifacts/nested_cross_val/model_cache_svm
  train_data_path: artifacts/nested_cross_val/data_for_final_train
  test_data_path: artifacts/nested_cross_val/data_for_final_train
  model_name: model.joblib
  metric_file_name_rf: artifacts/nested_cross_val/random_search_models/random_forest/metrics
  best_model_params_rf: artifacts/nested_cross_val/random_search_models/random_forest/best_model_params
  STATUS_FILE: artifacts/nested_cross_val/status.txt

#Changes will need to be done for model_trainer and model_evaluation as we are doing a nested cross validation
model_loader:
  root_dir: artifacts_deployment/model_loader
  model_path: artifacts/model_trainer/final_model.joblib
  STATUS_FILE: artifacts/model_trainer/status.txt

prediction:
  root_dir: artifacts_deployment/prediction
  data_dir: artifacts_deployment/feature_engineering/X.npz
  model_path: artifacts/model_trainer/final_model.joblib
  STATUS_FILE: artifacts_deployment/prediction/status.txt

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/feature_engineering
  model_path: artifacts/model_trainer/final_model.joblib
  metric_file: artifacts/model_evaluation/metrics
  STATUS_FILE: artifacts/model_evaluation/status.txt
  
